name: tourist_app
description: tourist_app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependency_overrides:
  intl: ^0.18.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_notch_bottom_bar:
    git:
      url: https://github.com/ngocsangair01/animated_notch_bottom_bar.git
  app_settings: ^4.2.0
  auto_size_text: ^3.0.0
  comment_box: ^0.0.18
  connectivity_plus: ^2.3.7
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  dotted_border: ^2.0.0+3
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_multi_formatter: ^2.10.2
  flutter_rounded_date_picker: ^3.0.2
  flutter_svg: ^1.1.6
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  http: ^0.13.5
  image_picker: ^0.8.7+1
  intl: ^0.18.0
  palette_generator: ^0.3.3+2
  permission_handler: ^10.2.0
  pull_to_refresh: ^2.0.0
  scrollable_positioned_list: ^0.2.3
  shimmer: ^2.0.0
  slugify: ^2.0.0
  syncfusion_flutter_charts: ^21.1.41
  tiengviet: ^0.5.0
  timeline_list: ^0.0.6
dev_dependencies:
  build_runner: ^2.3.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  flutter_chat_ui: 1.6.5
  flutter_lints: ^2.0.0
  flutter_local_notifications: ^13.0.0
  flutter_test:
    sdk: flutter
  table_calendar: ^3.0.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/Resource/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: InterBold
      fonts:
        - asset: asset/fonts/Inter-Bold.ttf

    - family: Inter
      fonts:
        - asset: asset/fonts/Inter-Regular.ttf

    - family: InterLight
      fonts:
        - asset: asset/fonts/Inter-Light.ttf

    - family: InterExtraLight
      fonts:
        - asset: asset/fonts/Inter-ExtraLight.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
